"""update

Revision ID: 7fa3ede2d9f4
Revises: 953b4177bb35
Create Date: 2024-09-10 16:28:32.084420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa3ede2d9f4'
down_revision = '953b4177bb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=225),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=225),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
