"""update

Revision ID: 953b4177bb35
Revises: 2ea74010b716
Create Date: 2024-09-10 15:35:48.105289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953b4177bb35'
down_revision = '2ea74010b716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
